### PR TITLE
Added dependency - type definitions for mocha.

### PR DESCRIPTION
**Pull request by rahulrkr08**
### Description

Fix to 'npm test' which gives error for todo-legacy service as because of missing types definitions for mocha. 

- connect to #71 
- [x] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@rahulrkr08 In order to take this PR, you'll need to sign the CLA, which you can find by clicking this link: https://cla.strongloop.com/agreements/strongloop/loopback-next-example

**Comment by kjdelisle** [comment]
Additionally, you'll need to rebase the pull request.

**Comment by rahulrkr08** [comment]
Will create new fresh pull request

**Pull request closed without merging**
