### PR TITLE
Adding dependency - type definitions for mocha.

### PR DESCRIPTION
**Pull request by rahulrkr08**
### Description

Fix to 'npm test' which gives error for todo-legacy service as because of missing types definitions for mocha. 

- connect to #71 
- [x] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by rahulrkr08** [comment]
@kjdelisle I have created new pull request for #72

**Comment by kjdelisle** [comment]
@rahulrkt08 You don't need to create new pull requests when the previous ones become out of date; see [this StackOverflow post](https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo) for an example of how to do it in the future.

**Comment by kjdelisle** [comment]
@rahulrkr08 You don't need to create new pull requests when the previous ones become out of date; see [this StackOverflow post](https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo) for an example of how to do it in the future.

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@rahulrkr08 Based on changes I had to make for #73, this PR is not required any longer. Sorry. :(

**Comment by rahulrkr08** [comment]
Closing pull request as already pushed changes with #73.

**Pull request closed without merging**
