### PR TITLE
Add package-lock files

### PR DESCRIPTION
**Pull request by kjdelisle**
As of npm@5.x, there are now package-lock files that get generated as a result of builds.
Since these lock files describe the *structure* of the dependency tree as well as the versions, npm recommends that these files be committed to your repository so that developers can work against identical dependency trees.

See https://docs.npmjs.com/files/package-locks for more info.

### CODE REVIEW

**Comment by kjdelisle** [comment]
Had to rebuild the commit; turns out it actually stores the registry address in the package-lock.json files, and I was using the staging registry at the time.

Something to watch out for, I guess?

**Comment by kjdelisle** [comment]
Odd. The tests are failing because `jq` is printing out usage?

@slnode test please

**Comment by IgorBelyi** [comment]
The problem is in `bin/get-account-summary` and `bin/get-account` scripts. Just add '.' to 'jq' which is the simplest filter you can get.

**Comment by superkhau** [comment]
@IgorBelyi Thanks for chiming in. What do you mean by add . to jq?

**Comment by superkhau** [comment]
I'm assuming `... | jq .`?

**Comment by bajtos** [comment]
FWIW, by using package-lock files, we will be running our tests against a possibly different set of dependencies than our users will get installed by `npm install`. As a result, we may start receiving bug reports that we won't be able to reproduce locally until we delete package-lock files or explicitly upgrade dependencies to their latest versions (which is usually not obvious, especially not for junior developers). The problem can be solved by configuring a service that will periodically send pull requests updating `package-lock` files, e.g. GreenKeeper. Unfortunately, GreenKeeper does not support monorepos (see https://github.com/greenkeeperio/greenkeeper/issues/139) yet.

I personally prefer to disable package-lock files completely. IMO, lock files are useful when developing applications, but not so much for module developers.

**Pull request merged**
